name: Build and Deploy the application
on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: kundankkkrishna/newapp:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Pull Docker image
        run: docker pull docker.io/kundankkkrishna/newapp:latest
        
#       - name: delete previous deployments
#         run: kubectl delete -f kube
      - name: check directory
        run: pwd && ls -al $(pwd)

      - name: stetup minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy to minikube
        run: |
          kubectl apply -f kube
        
      - name: Test service URLs
        run: |
            minikube service list
            kubectl describe service myservice
